
services:
  fastify:
    build: ./simple/fastify/
    container_name: fastify
    ports:
      - "3000:3000"
    networks:
      - tranet
      restart: always

  nginx:
      build: ./simple/nginx/
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    env_file: .env
    depends_on:
      - fastify
    networks:
      - tranet
    restart: always

    # image: nginx:stable
    # container_name: nginx
    # ports:
    #   - "8080:80"
    # volumes:
    #   - ./simple/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    # depends_on:
    #   - fastify
    # networks:
    #   - tranet

networks:
  tranet:
    name: tranet
    driver: bridge

# volumes:
#   wordpress:
#     name: wordpress
#     driver: local
#     driver_opts:
#       device: /home/${LOGNAME}/data/wordpress
#       o: bind
#       type: none
#
#   mariadb:
#     name: mariadb
#     driver: local
#     driver_opts:
#       device: /home/${LOGNAME}/data/mariadb
#       o: bind
#       type: none
#
# secrets:
#   db_root_pwd:
#     file: ../secrets/db_root_pwd.txt
#   db_user_pwd:
#     file: ../secrets/db_user_pwd.txt
#   wp_adm_pwd:
#     file: ../secrets/wp_adm_pwd.txt
#   wp_author_pwd:
#     file: ../secrets/wp_author_pwd.txt
#   redis_pwd:
#     file: ../secrets/redis_pwd.txt
#   ftp_pwd:
#     file: ../secrets/ftp_pwd.txt
#   gf_admin_pwd:
#     file: ../secrets/gf_admin_pwd.txt
#   gf_db_pwd:
#     file: ../secrets/gf_db_pwd.txt
