version: "3.8"

services:
  nginx:
    build: ./requirements/nginx/
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./web:/var/www/html
    env_file: .env
    networks:
      - inception
    restart: always

  wordpress:
    build: ./requirements/wordpress/
    container_name: wordpress
    volumes:
      - ./web:/var/www/html
    env_file: .env
    networks:
      - inception
    restart: always

  mariadb:
    build: ./requirements/mariadb/
    container_name: mariadb
    env_file: .env
    networks:
      - inception
    restart: always

networks:
  inception:
    name: inception

