volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/${LOGNAME}/data/wordpress
      o: bind
      type: none

  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/${LOGNAME}/data/mariadb
      o: bind
      type: none

services:
  nginx:
    build: ./requirements/nginx/
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    env_file: .env
    networks:
      - inception
    restart: always

  wordpress:
    build: ./requirements/wordpress/
    container_name: wordpress
    volumes:
      - wordpress:/var/www/html
    env_file: .env
    networks:
      - inception
    restart: always

  mariadb:
    build: ./requirements/mariadb/
    container_name: mariadb
    env_file: .env
    networks:
      - inception
    restart: always

networks:
  inception:
    name: inception

